### ISSUE TITLE
Tipuri Nomenclatoare

### ISSUE THREAD

**Issue by DianaBut** [WizromSoftware/Groupama#3]
1. Nu-si ia id-ul la rand din TableSYSInfo_NextId. Pot sa introduc prin interfata.

**Comment by LeonardMs** [comment]
Trebuie rulat pe baza de date urmatorul script.

alter PROCEDURE GetNextId
@tableName varchar(200), 
@nrInreg int
as begin

declare @cnt int;

select @cnt = count(*) from TableSYSInfo_NextId where TableName = @tableName;
if @cnt = 0 
begin 
  /*nu mai exista inregistrare pentru numele tabelei trimis ca parametru*/
  insert into TableSYSInfo_NextId(TableName, NextId)
  values(@tableName, 1);  
end;

update TableSYSInfo_NextId
    set NextId = NextId + @nrInreg 
  where TableName = @tableName;

END;

**Comment by DianaBut** [comment]
Tot nu ia Id-urile la rand. In TableSYSInfo_NextId - AvsXDec_Document are 4 pe NextId. Eu in interfata am 10.
![err pe tip nomen](https://cloud.githubusercontent.com/assets/19184622/15039289/7f8ca7fc-12b4-11e6-8aa2-52737c422d5e.png)

**Comment by LeonardMs** [comment]
Diana,

Te rog sa rulezi pe baza scriptul de mai jos


alter PROCEDURE GetNextId
 @tableName varchar(200), 
 @nrInreg int
 as begin

declare @cnt int;

select @cnt = count(*) from TableSYSInfo_NextId where TableName = @tableName;
 if @cnt = 0 
 begin 
 /*nu mai exista inregistrare pentru numele tabelei trimis ca parametru*/
 insert into TableSYSInfo_NextId(TableName, NextId)
 values(@tableName, 1);
 end;

 declare @idTable int, @idAsignat int;
 select @idAsignat = max(NextId) from TableSYSInfo_NextId  (nolock) where TableName = @tableName;
 if @tableName = 'AvsXDec_Dictionary'
 begin
	select @idTable = max(isnull(DictionaryId, 0)) from AvsXDec_Dictionary (nolock);
 end
 if @tableName = 'AvsXDec_Dictionary'
 begin
	select @idTable = max(isnull(DictionaryItemId, 0)) from AvsXDec_DictionaryItem (nolock);
 end
 if @tableName = 'AvsXDec_Document'
 begin
	select @idTable = max(isnull(DocumentId, 0)) from AvsXDec_Document (nolock);
 end
  if @tableName = 'AvsXDec_AvansDetail'
 begin
	select @idTable = max(isnull(DocumentDetailId, 0)) from AvsXDec_AvansDetail (nolock);
 end
  if @tableName = 'AvsXDec_DecontDetail'
 begin
	select @idTable = max(isnull(DocumentDetailId, 0)) from AvsXDec_DecontDetail (nolock);
 end
  if @tableName = 'AvsXDec_AccountingPeriod'
 begin
	select @idTable = max(isnull(PeriodOfAccountId, 0)) from AvsXDec_AccountingPeriod (nolock);
 end
 if @tableName = 'AvsXDec_AccountingYear'
 begin
	select @idTable = max(isnull(AccPeriodId, 0)) from AvsXDec_AccountingYear (nolock);
 end
 if @tableName = 'AvsXDec_BankComission'
 begin
	select @idTable = max(isnull(ComissionId, 0)) from AvsXDec_BankComission (nolock);
 end
 if @tableName = 'AvsXDec_BusinessTransaction'
 begin
	select @idTable = max(isnull(TransactionId, 0)) from AvsXDec_BusinessTransaction (nolock);
 end
 if @tableName = 'AvsXDec_Circuit'
 begin
	select @idTable = max(isnull(CircuitId, 0)) from AvsXDec_Circuit (nolock);
 end
 if @tableName = 'AvsXDec_DocumentStateHistory'
 begin
	select @idTable = max(isnull(Id, 0)) from AvsXDec_DocumentStateHistory (nolock);
 end
 if @tableName = 'AvsXDec_DocumentType'
 begin
	select @idTable = max(isnull(DocumentTypeId, 0)) from AvsXDec_DocumentType (nolock);
 end
 if @tableName = 'AvsXDec_relUploadDocumente'
 begin
	select @idTable = max(isnull(IdAuto, 0)) from AvsXDec_relUploadDocumente (nolock);
 end
 
 if @idAsignat < @idTable
 begin
	update TableSYSInfo_NextId
	set NextId = @idTable
	where TableName = @tableName
 end;

update TableSYSInfo_NextId
 set NextId = NextId + @nrInreg 
 where TableName = @tableName;

END;

**Comment by LeonardMs** [comment]
alter PROCEDURE GetNextId
 @tableName varchar(200), 
 @nrInreg int
 as begin

declare @cnt int;

select @cnt = count(*) from TableSYSInfo_NextId where TableName = @tableName;
 if @cnt = 0 
 begin 
 /*nu mai exista inregistrare pentru numele tabelei trimis ca parametru*/
 insert into TableSYSInfo_NextId(TableName, NextId)
 values(@tableName, 1);
 end;

 declare @idTable int, @idAsignat int;
 select @idAsignat = max(NextId) from TableSYSInfo_NextId  (nolock) where TableName = @tableName;
 if @tableName = 'AvsXDec_Dictionary'
 begin
	select @idTable = max(isnull(DictionaryId, 0)) from AvsXDec_Dictionary (nolock);
 end
 if @tableName = 'AvsXDec_DictionaryItem'
 begin
	select @idTable = max(isnull(DictionaryItemId, 0)) from AvsXDec_DictionaryItem (nolock);
 end
 if @tableName = 'AvsXDec_Document'
 begin
	select @idTable = max(isnull(DocumentId, 0)) from AvsXDec_Document (nolock);
 end
  if @tableName = 'AvsXDec_AvansDetail'
 begin
	select @idTable = max(isnull(DocumentDetailId, 0)) from AvsXDec_AvansDetail (nolock);
 end
  if @tableName = 'AvsXDec_DecontDetail'
 begin
	select @idTable = max(isnull(DocumentDetailId, 0)) from AvsXDec_DecontDetail (nolock);
 end
  if @tableName = 'AvsXDec_AccountingPeriod'
 begin
	select @idTable = max(isnull(PeriodOfAccountId, 0)) from AvsXDec_AccountingPeriod (nolock);
 end
 if @tableName = 'AvsXDec_AccountingYear'
 begin
	select @idTable = max(isnull(AccPeriodId, 0)) from AvsXDec_AccountingYear (nolock);
 end
 if @tableName = 'AvsXDec_BankComission'
 begin
	select @idTable = max(isnull(ComissionId, 0)) from AvsXDec_BankComission (nolock);
 end
 if @tableName = 'AvsXDec_BusinessTransaction'
 begin
	select @idTable = max(isnull(TransactionId, 0)) from AvsXDec_BusinessTransaction (nolock);
 end
 if @tableName = 'AvsXDec_Circuit'
 begin
	select @idTable = max(isnull(CircuitId, 0)) from AvsXDec_Circuit (nolock);
 end
 if @tableName = 'AvsXDec_DocumentStateHistory'
 begin
	select @idTable = max(isnull(Id, 0)) from AvsXDec_DocumentStateHistory (nolock);
 end
 if @tableName = 'AvsXDec_DocumentType'
 begin
	select @idTable = max(isnull(DocumentTypeId, 0)) from AvsXDec_DocumentType (nolock);
 end
 if @tableName = 'AvsXDec_relUploadDocumente'
 begin
	select @idTable = max(isnull(IdAuto, 0)) from AvsXDec_relUploadDocumente (nolock);
 end
 
 if @idAsignat < @idTable
 begin
	update TableSYSInfo_NextId
	set NextId = @idTable
	where TableName = @tableName
 end;

update TableSYSInfo_NextId
 set NextId = NextId + @nrInreg 
 where TableName = @tableName;

END;

**Comment by DianaBut** [comment]
E OK.
