### ISSUE TITLE
Plata pentru financiat

### ISSUE THREAD

**Issue by DianaBut** [WizromSoftware/Groupama#4]
La deschiderea meniului apare aceasta eroare:
![eroare plata financiar](https://cloud.githubusercontent.com/assets/19184622/15010875/44fbf7cc-11f7-11e6-9027-15b04c240499.png)

**Comment by LeonardMs** [comment]
Trebuie rulat pe baza de date urmatorul script:

/*functie */
create function fcnAvsXDec_GetComisionBancar( @ValPlata decimal(18,4), @CurrencyIdPlata int, @BankIdPlata int)
returns decimal
as begin
	
	/*functie care calculeaza comisionul in functie de suma ce trebuie platita si
	banca care se trimite ca si parametru*/
	declare @comisionBancar decimal(18,4);
	declare @cnt int;

	select @cnt = COUNT(*) from vwAvsXDec_BankComission where BankId = @BankIdPlata;
	if @cnt = 0
	/*nu am gasit setari la nivel de banca=> comision = 0*/
	begin
		set @comisionBancar = 0;
	end
	else begin
		select @cnt = COUNT(*) from vwAvsXDec_BankComission bc where bc.BankId = @BankIdPlata and bc.MinimumPay = -99 and bc.MaximumPay = -99;
		if @cnt <> 0
		begin
			/*comisionul se acorda per plata*/
			select @comisionBancar = bc.ComissionValue from vwAvsXDec_BankComission bc where bc.BankId = @BankIdPlata and bc.MinimumPay = -99 and bc.MaximumPay = -99;
		end
		else begin
			/*comisionul se acorda per trepte de valori plata*/
			select @comisionBancar = ISNULL(max(bc.ComissionValue), 0) from vwAvsXDec_BankComission bc
					where bc.BankId = @BankIdPlata
					and @ValPlata between bc.MinimumPay and bc.MaximumPay;
		end
	end;

	return @comisionBancar;
end;



/*view*/

create view vwAvsXDec_DocumenteRestPlata as 
select av.DocumentId, av.DocumentStateId, av.DocumentState, av.DocumentTypeId, av.DocumentTypeCode, av.DocumentTypeName,
		av.DocumentDate, av.TotalAmount, av.CurrencyId, av.CurrencyCode, av.UnconfRestAmount,
		av.BankId, av.BankName, av.SucursalaId, av.SucursalaName, dbo.fcnAvsXDec_GetComisionBancar(av.UnconfRestAmount, av.CurrencyId, av.BankId) as TotalComissionPayment, 
		av.CurrencyId as PaymentCurrencyId, av.CurrencyCode as PaymentCurrencyCode, av.PaymentDate
from vwAvsXDec_Avans av
where ISNULL(av.UnconfRestAmount, 100) <> 0
union all
select dec.DocumentId, dec.DocumentStateId, dec.DocumentState, dec.DocumentTypeId, dec.DocumentTypeCode, dec.DocumentTypeName,
		dec.DocumentDate, dec.TotalAmount, dec.CurrencyId, dec.CurrencyCode, dec.UnconfRestAmount,
		dec.BankId, dec.BankName, dec.SucursalaId, dec.SucursalaName, dbo.fcnAvsXDec_GetComisionBancar(dec.UnconfRestAmount, dec.CurrencyId, dec.BankId) as TotalComissionPayment,
		dec.CurrencyId as PaymentCurrencyId, dec.CurrencyCode as PaymentCurrencyCode, dec.PaymentDate
from vwAvsXDec_Decont dec
where ISNULL(dec.UnconfRestAmount, 100) <>0

**Comment by DianaBut** [comment]
Este ok. Mai trebuie marit ecranul sau gridul. Nu se vad toate datele din coloane.

**Comment by LeonardMs** [comment]
Pe ftp se afla ultima versiune. 
Se poate verifica.

**Comment by DianaBut** [comment]
e ok
